version: "2.3"

services:

  backend:
    command: /app/docker/scripts/startup.sh npm run start
    build:
      context: .
    environment:
      DB_URI: postgres://postgres:password@postgres:5432/guitarhorse
      DEBUG: 'knex:query'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - "$PWD/src:/app/src"
      - "$PWD/tools:/app/tools"
  postgres:
    image: postgres:latest
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guitarhorse
