organisation:
  name:
    type: string
  address:
    type: string
  postcode:
    type: number
    maximum: 9999

service:
  name:
    type: string
  address:
    type: string
  postcode:
    type: number
    maximum: 9999
